#!/usr/bin/env python3
import mechanicalsoup
import os
import yaml
import stat

CONFIG_PATH = os.path.expanduser('~') + '/.pow.yml'
config = {
    'username': '',
    'password': '',
}
if os.path.isfile(CONFIG_PATH) and os.path.getsize(CONFIG_PATH) is not 0:
    with open(CONFIG_PATH, 'r') as f:
        config = yaml.load(f)
else:
    config = {key: input(key + ': ') for key in config.keys()}
    with open(CONFIG_PATH, 'w') as f:
        yaml.dump(config, f)
    os.chmod(CONFIG_PATH, stat.S_IRUSR | stat.S_IRUSR)

# Check if group or public can read config and the private details therein.
# If so, warn user.
if os.stat(CONFIG_PATH).st_mode & (stat.S_IRGRP | stat.S_IROTH):
    print('Warning: config file may be accessible by other users.', file=sys.stderr)

# Load PowerSchool login page
browser = mechanicalsoup.StatefulBrowser()
browser.set_verbose(2)
browser.open('https://ps.fccps.org')

buttons = browser.get_current_page().find_all('button')
for b in buttons:
    print(b)
# Fill in login form
form = browser.select_form('#LoginForm')
print(form.print_summary())
# so much blood
form.choose_submit('#btn-powerschool-id')
browser['account'] = config['username']
browser['pw'] = config['password']
resp = browser.submit_selected()

# Verify we're in
page = browser.get_current_page()
#print(page)
messages = page.find_all('td')
print(len(messages))
for message in messages:
    print(message.text)
